Feat/network box
platypus-finance/frontend pull request #5
Opened 2021-07-22 14:59 UTC by ChrisChan888

According to the link below, Ethereum cannot use "wallet_addEthereumChain" event.
https://stackoverflow.com/questions/66588495/switch-metamask-network-to-chain-1-ethereum-mainnet

2021-07-22 15:38 UTC, whisidev commented
/preview

2021-07-22 15:52 UTC, whisidev requested changes
please see comments.

2021-07-22 15:52 UTC, whisidev commented on src/config/network.ts
> +    ethereum
in the doc, they suggested using wallet_switchEthereumChain first, and wallet_addEthereumChain as a fallback
https://docs.metamask.io/guide/rpc-api.html#usage-with-wallet-switchethereumchain

can you try this?

2021-07-22 15:52 UTC, whisidev commented on src/config/network.ts
> +export const getNetwork = (chainId: number): Network | null => {
`switchNetwork` and `getNetwork`are functions, not constants. Probably better to put them in `src/utils/networks`

2021-07-22 15:52 UTC, whisidev commented on src/config/network.ts
> +  ETHEREUM = 1 as any,
is there any way we can avoid using `any`? as it's not a good practice in typescript

2021-07-25 11:19 UTC, whisidev commented on src/utils/network.ts
> +export const getNetwork = (chainId: number): Network | null => {
avoid hardcoding the chainId in switch's cases, because it will be easier to add more supported network. May do something like the following

```
export const getNetwork = (chainId: ChainId): Network | null => {
  // select network by chainId
  if (chainId in ChainId) {
    return NETWORKS[chainId]
  } else {
    return null
  }
}
```

2021-07-25 11:28 UTC, whisidev commented on src/config/network.ts
> +  ETHEREUM = 1 as any,
shouldn't need `as any`? the following work?

```
  ETHEREUM = 1,
  AVALANCHE = 43114,
  BSC = 56,
```

2021-07-25 11:29 UTC, whisidev requested changes
looks good. please see comments for the suggested minor changes

2021-07-28 00:58 UTC, ChrisChan888 commented on src/config/network.ts
> +  ETHEREUM = 1 as any,
Removed.
I thought only add "as any" which gets the string key by value.
```typescript
interface SelectNetworkBoxProps {
  chainId: ChainId
}
export const SelectNetworkBox: React.FC<SelectNetworkBoxProps> = (
  props: SelectNetworkBoxProps,
) => {
  return (
    <SelectNetworkBoxContainer onClick={() => switchNetwork(props.chainId)}>
      Switch to {ChainId[props.chainId]}
    </SelectNetworkBoxContainer>
  )
}

```

2021-07-28 01:05 UTC, ChrisChan888 commented on src/utils/network.ts
> +export const getNetwork = (chainId: number): Network | null => {
changed

2021-07-28 15:52 UTC, whisidev approved these changes

2021-07-28 15:58 UTC, merged