add typechain, config/contracts and utils/contract for create minttokenbox
platypus-finance/frontend pull request #9
Opened 2021-08-04 15:20 UTC by ChrisChan888

- add typechain to post install
- get contract instance from config/contracts
- create minttokenbox component

2021-08-05 08:11 UTC, whisidev requested changes
see comments

2021-08-05 08:11 UTC, whisidev commented on src/config/contracts.ts
> +export const getDAIInstance = (): DAI | null => {
Cam combine the two functions into one? getTestTokenInstance(Address tokenAddress): TestERC20

we don’t wanna create one function for each token because it will be tedious and error prone when we have a lot of tokens.

2021-08-05 12:40 UTC, ChrisChan888 commented on src/config/contracts.ts
> +export const getDAIInstance = (): DAI | null => {
Wrote a class and pack them to a token Object!

2021-08-05 12:41 UTC, ChrisChan888 commented on src/config/contracts.ts
> +export const getDAIInstance = (): DAI | null => {
There seem have no TestERC20 type.

2021-08-05 15:39 UTC, whisidev commented on src/config/contracts/token.ts
> +      switch (this.symbol) {
don't need the switch

2021-08-05 15:42 UTC, whisidev commented on src/constants/abis/DAI.json
> +{
don't need this file, because we treat all tokens as ERC20.

2021-08-05 15:43 UTC, whisidev commented on src/constants/abis/USDT.json
> +{
don't need this file, because we treat all tokens as ERC20.

2021-08-06 06:54 UTC, whisidev approved these changes
LGTM

2021-08-06 09:54 UTC, merged